export type BusinessStatus = 'draft' | 'published';

export interface Business {
    id: string;
    created_at: string;
    updated_at: string;
    created_by: string | null;
    slug: string;

    // Info (PT-BR is base)
    business_name: string;
    business_name_ja?: string;
    business_name_en?: string;

    description_short: string;
    description_short_ja?: string;
    description_short_en?: string;

    description_long: string | null;
    description_long_ja?: string | null;
    description_long_en?: string | null;

    category: string;
    tags: string[] | null;
    featured: boolean;
    status: BusinessStatus;

    // Location
    address_line1: string;
    address_line1_ja?: string;
    address_line1_en?: string;

    address_line2: string | null;
    neighborhood: string | null;
    city: string;
    city_ja?: string;
    city_en?: string;
    prefecture: string;
    prefecture_ja?: string;
    prefecture_en?: string;
    postal_code: string;
    country: string;
    google_maps_url: string | null;
    latitude: number | null;
    longitude: number | null;

    // Contact
    phone: string | null;
    whatsapp: string | null;
    email: string | null;
    website_url: string | null;
    instagram_url: string | null;
    line_url: string | null;

    // Media
    logo_url: string | null;
    cover_image_url: string | null;
    gallery_images: string[] | null;
    presentation_url: string | null;
    // map_image_url: string | null; // DEPRECATED - No longer used in the UI

    // Operation
    opening_hours: Record<string, string> | null; // e.g. { "monday": "09:00 - 18:00" } or structured
    price_range: string | null;
    languages_supported: string[] | null;
    view_count?: number;
}

export type BusinessFormData = Omit<Business, 'id' | 'created_at' | 'updated_at' | 'created_by' | 'slug'> & {
    slug?: string; // Optional in form, generated by backend logic if missing, but we handle it in service
};
